import time
from funcs import generate_ssns, generate_unique_ssns

print("Generate ssns results: ")
start = time.time()
print(generate_ssns(1000))
end = time.time()
print("Time elapsed: "+str(end-start)+" seconds")
start = time.time()
print(generate_ssns(10000))
end = time.time()
print("Time elapsed: "+str(end-start)+" seconds")
start = time.time()
print(generate_ssns(100000))
end = time.time()
print("Time elapsed: "+str(end-start)+" seconds")

print("-----------------------")
print("Generate unique ssns for males results: ")
start = time.time()
print(generate_unique_ssns(1000, "male", "1990-01-01", "1990-01-19"))
end = time.time()
print("Time elapsed: "+str(end-start)+" seconds")
start = time.time()
print(generate_unique_ssns(10000, "male", "1990-01-01", "1990-01-19"))
end = time.time()
print("Time elapsed: "+str(end-start)+" seconds")
start = time.time()
print(generate_unique_ssns(100000, "male", "1990-01-01", "1990-01-19"))
end = time.time()
print("Time elapsed: "+str(end-start)+" seconds")

print("-----------------------")
print("Generate unique ssns for females results: ")
start = time.time()
print(generate_unique_ssns(1000, "female", "1990-01-01", "1990-01-19"))
end = time.time()
print("Time elapsed: "+str(end-start)+" seconds")
start = time.time()
print(generate_unique_ssns(10000, "female", "1990-01-01", "1990-01-19"))
end = time.time()
print("Time elapsed: "+str(end-start)+" seconds")
start = time.time()
print(generate_unique_ssns(100000, "female", "1990-01-01", "1990-01-19"))
end = time.time()
print("Time elapsed: "+str(end-start)+" seconds")
